use chrono::{Datelike, Duration, Local, NaiveDate};
use eframe::egui::{self, Color32};
use models::*;
use std::collections::HashSet;
use storage::*;
use theme::{bg, muted, set_theme, AMBER, GREEN, RED_IAM};
use ui::{
    contrats::page_contrats, disponibilite::page_disponibilite, maintenance::page_maintenance,
    modals::render_modals, nouveau_contrat::page_nouveau_contrat, sidebar::render_sidebar,
    tableau::page_tableau, ventes::page_ventes, voitures::page_voitures,
};
use ui_helpers::*;

pub struct App {
    pub onglet: Onglet,
    pub onglet_prec: Option<Onglet>,
    pub voitures: Vec<Voiture>,
    pub contrats: Vec<Contrat>,
    pub f_numero: String,
    pub f_voiture: usize,
    pub f_voiture_note: String,
    pub f_voiture_search: String,
    pub f_client: String,
    pub f_tel: String,
    pub f_agent: String,
    pub f_debut: String,
    pub f_fin: String,
    pub f_km_dep: String,
    pub f_km_ret: String,
    pub f_tarif: String,
    pub f_notes: String,
    pub f_montant_paye: String,
    pub f_msg: String,
    pub f_ok: bool,
    pub f_en_edition: Option<usize>,
    pub f_car_error_cleared: bool,
    pub d_du: String,
    pub d_au: String,
    pub d_ids: Vec<u64>,
    pub d_fait: bool,
    pub d_erreur: String,
    pub d_recherche_modele: String,
    pub d_modele_periode: Vec<(u64, String, String, String)>,
    pub c_recherche: String,
    pub c_statut: usize,
    pub c_suppr: Option<usize>,
    pub c_page: usize,
    pub c_filter_mois: usize,
    pub c_filter_annee: String,
    pub v_modele: String,
    pub v_plaque: String,
    pub v_annee: String,
    pub v_cat: String,
    pub v_couleur: String,
    pub v_tarif: String,
    pub v_msg: String,
    pub v_ok: bool,
    pub v_recherche: String,
    pub v_page: usize,
    pub v_edit_id: Option<u64>,
    pub v_edit_modele: String,
    pub v_edit_plaque: String,
    pub v_edit_annee: String,
    pub v_edit_cat: String,
    pub v_edit_couleur: String,
    pub v_edit_tarif: String,
    pub v_edit_etat: String,
    pub v_suppr_confirm: Option<u64>,
    pub ventes: Vec<VoitureVente>,
    pub vt_nom: String,
    pub vt_plaque: String,
    pub vt_chassis: String,
    pub vt_immat: String,
    pub vt_annee: String,
    pub vt_prix_achat: String,
    pub vt_prix_demande: String,
    pub vt_notes: String,
    pub vt_msg: String,
    pub vt_ok: bool,
    pub vt_recherche: String,
    pub vt_page: usize,
    pub vt_suppr_confirm: Option<u64>,
    pub vt_marquer_vendu: Option<u64>,
    pub vt_prix_vendu_input: String,
    pub modal_voiture: ModalVoiture,
    pub modal_contrat: ModalContrat,
    pub tb_filter: usize,
    pub tb_page: usize,
    pub dark_mode: bool,
    pub alerte_retour_ok: HashSet<u64>,
    pub tb_date_recherche: String,
    pub reparations: Vec<Reparation>,
    pub rep_voiture_idx: usize,
    pub rep_date: String,
    pub rep_description: String,
    pub rep_prix: String,
    pub rep_observation: String,
    pub rep_msg: String,
    pub rep_ok: bool,
    pub rep_filtre_voiture: usize,
    pub rep_recherche: String,
    pub rep_suppr_confirm: Option<u64>,
}

impl App {
    pub fn new() -> Self {
        let mut a = Self {
            onglet: Onglet::Tableau,
            onglet_prec: None,
            voitures: charger(&cars_file()),
            contrats: charger(&rentals_file()),
            f_numero: String::new(),
            f_voiture: 0,
            f_voiture_note: String::new(),
            f_voiture_search: String::new(),
            f_client: String::new(),
            f_tel: String::new(),
            f_agent: String::new(),
            f_debut: aujourd_hui(),
            f_fin: dans_7j(),
            f_km_dep: "0".into(),
            f_km_ret: "0".into(),
            f_tarif: String::new(),
            f_notes: String::new(),
            f_montant_paye: "0".into(),
            f_msg: String::new(),
            f_ok: false,
            f_en_edition: None,
            f_car_error_cleared: false,
            d_du: aujourd_hui(),
            d_au: dans_7j(),
            d_ids: vec![],
            d_fait: false,
            d_erreur: String::new(),
            d_recherche_modele: String::new(),
            d_modele_periode: vec![],
            c_recherche: String::new(),
            c_statut: 0,
            c_suppr: None,
            c_page: 0,
            c_filter_mois: 0,
            c_filter_annee: String::new(),
            v_modele: String::new(),
            v_plaque: String::new(),
            v_annee: Local::now().year().to_string(),
            v_cat: "Berline".into(),
            v_couleur: String::new(),
            v_tarif: "3000".into(),
            v_msg: String::new(),
            v_ok: false,
            v_recherche: String::new(),
            v_page: 0,
            v_edit_id: None,
            v_edit_modele: String::new(),
            v_edit_plaque: String::new(),
            v_edit_annee: String::new(),
            v_edit_cat: String::new(),
            v_edit_couleur: String::new(),
            v_edit_tarif: String::new(),
            v_edit_etat: String::new(),
            v_suppr_confirm: None,
            ventes: charger(&ventes_file()),
            vt_nom: String::new(),
            vt_plaque: String::new(),
            vt_chassis: String::new(),
            vt_immat: String::new(),
            vt_annee: Local::now().year().to_string(),
            vt_prix_achat: String::new(),
            vt_prix_demande: String::new(),
            vt_notes: String::new(),
            vt_msg: String::new(),
            vt_ok: false,
            vt_recherche: String::new(),
            vt_page: 0,
            vt_suppr_confirm: None,
            vt_marquer_vendu: None,
            vt_prix_vendu_input: String::new(),
            modal_voiture: ModalVoiture::default(),
            modal_contrat: ModalContrat::default(),
            tb_filter: 0,
            tb_page: 0,
            dark_mode: false,
            alerte_retour_ok: HashSet::new(),
            tb_date_recherche: String::new(),
            reparations: charger(&reparations_file()),
            rep_voiture_idx: 0,
            rep_date: aujourd_hui(),
            rep_description: String::new(),
            rep_prix: String::new(),
            rep_observation: String::new(),
            rep_msg: String::new(),
            rep_ok: false,
            rep_filtre_voiture: 0,
            rep_recherche: String::new(),
            rep_suppr_confirm: None,
        };
        if a.voitures.is_empty() {
            a.voitures = voitures_defaut();
            sauvegarder(&cars_file(), &a.voitures);
        }
        for v in &mut a.voitures {
            if v.etat.is_empty() {
                v.etat = "Bon état".to_string();
            }
        }
        a
    }
